DROP DATABASE GREENHOUSE;
-- CRIA DATABASE
CREATE DATABASE GREENHOUSE;
-- DEFINE COMO TRABALHO
USE GREENHOUSE;
-- CRIA TABELA
CREATE TABLE `GREENHOUSE`.`PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp,
    `SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
    PRIMARY KEY `PK_PLANT_NAME` (`PLANT_NAME`)
);
-- INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Orquídea", 10, "HIGH");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Rosa", 11, "LOW");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Babosa", 20, "MID");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Girassol", 10, "LOW");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Margarida", 6, "MID");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Cannabis", 420, "HIGH");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Tulipa", 24, "LOW");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Copo-de-leite", 16, "LOW");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Videira", 19, "MID");
INSERT INTO `GREENHOUSE`.`PLANTS` (`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`) VALUES("Macieira", 22, "LOW");

-- COMANDO SELECT
-- consultando tudo da tabela
SELECT * FROM `GREENHOUSE`.`PLANTS`;
-- COLUNA DESEJADA
SELECT `SENSOR_VALUE` FROM `GREENHOUSE`.`PLANTS`;
-- ESPECIFICA
SELECT `PLANT_NAME`,`SENSOR_VALUE`,`SENSOR_EVENT` FROM `GREENHOUSE`.`PLANTS` WHERE `SENSOR_VALUE` < 15 AND `SENSOR_LEVEL` = "LOW";

SELECT * FROM PLANTS WHERE SENSOR_LEVEL IN ("HIGH","LOW");

-- ORDENAÇÃO
SELECT * FROM PLANTS WHERE SENSOR_VALUE < 420 ORDER BY SENSOR_VALUE DESC;

-- AGRUPAMENTO
SELECT COUNT(*),SENSOR_LEVEL FROM PLANTS GROUP BY SENSOR_LEVEL;
-- TOP
SELECT `PLANT_NAME`,`SENSOR_VALUE` FROM `PLANTS` LIMIT 3;
-- MIN AND MAX
SELECT PLANT_NAME, SENSOR_VALUE FROM PLANTS WHERE SENSOR_VALUE = (SELECT MIN(SENSOR_VALUE) FROM PLANTS);
SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_LEVEL FROM PLANTS WHERE SENSOR_VALUE = (SELECT MAX(SENSOR_VALUE) FROM PLANTS);
-- SUM
SELECT SUM(SENSOR_VALUE) FROM PLANTS;
-- AVG
SELECT AVG(SENSOR_VALUE) FROM PLANTS;
-- LIKE
SELECT `PLANT_NAME`,`SENSOR_EVENT` FROM PLANTS WHERE PLANT_NAME LIKE '__r%';

-- UPDATE
SELECT * FROM PLANTS;
UPDATE PLANTS SET SENSOR_LEVEL = "LOW", SENSOR_VALUE = 34 WHERE PLANT_NAME = "Babosa";
-- DELETE
DELETE FROM PLANTS WHERE PLANT_NAME = "Cannabis"
