DROP DATABASE UNOESC_BANK;
CREATE DATABASE UNOESC_BANK;
USE UNOESC_BANK;

CREATE TABLE CLIENTE(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE CONTA(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    NRO_CONTA VARCHAR(10) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    constraint FK_ID_CLIENTE_CONTA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE TRANSACAO(
	ID INT NOT NULL auto_increment PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    TIPO_TRANSACAO INT NOT NULL,
    DATA_HORA datetime NOT NULL,
    VALOR FLOAT NOT NULL
);

-- DEFININDO UMA FK POSTERIORMENTE A CRIAÇÃO DA TABELA
ALTER TABLE TRANSACAO ADD foreign key (ID_CONTA) REFERENCES CONTA(ID);

-- CRIANDO INDICES
CREATE INDEX IDX_TRANSACAO_TP_TRANSACAO ON TRANSACAO(TIPO_TRANSACAO);

CREATE INDEX IDX_TRANSACAO_TP_DATA_HORA ON TRANSACAO(DATA_HORA);

CREATE TABLE CARTEIRA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    SALDO FLOAT NOT NULL,
    CONSTRAINT FK_ID_CONTA_CARTEIRA FOREIGN KEY(ID_CONTA) REFERENCES CONTA(ID)
);