-- EXCLUINDO BD
DROP DATABASE `BD2401` ;
-- CRIANDO SCHEMA DO BD
CREATE SCHEMA `BD2401` ;
-- CRIANDO TABELA
CREATE TABLE `BD2401`.`NEW_TABLE` (
	`ID_MEMBER` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(50) NOT NULL ,
    `ACTIVE` BIT(1) NULL DEFAULT 1,
    `WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`ID_MEMBER`)
);
-- inserindo dados na tabela
INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`)
VALUES ('Samuel De Lorenzi Ribeiro');

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES ('Alexandre José Ribeiro', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES ('Kauã Camargo', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES ('Leonardo Zonta', 0);

-- EXIBINDO/CONSULTANDO DADOS
SELECT * FROM `BD2401`.`NEW_TABLE`;