-- criando view personalizada

CREATE VIEW DaysOfWeek AS
SELECT "SEGUNDA-FEIRA"
UNION
SELECT "TERÇA-FEIRA"
UNION
SELECT "QUARTA-FEIRA"
UNION
SELECT "QUINTA-FEIRA"
UNION
SELECT "SEXTA-FEIRA"
UNION
SELECT "SÁBADO"
UNION
SELECT "DOMINGO";